### PR TITLE
Fix error when review does not reference a commit

### LINKED ISSUE #239: no incoming PRs
I have no incoming PRs. I seem to be getting a 500 error on the incoming request.

```
GET https://github-health.appspot.com/api/dash/incoming 500 ()  dash.mjs:282 
(anonymous) @ dash.mjs:282
(anonymous) @ dash.mjs:6
__awaiter @ dash.mjs:2
getAndRenderIncoming @ dash.mjs:281
(anonymous) @ dash.mjs:260
(anonymous) @ dash.mjs:6
__awaiter @ dash.mjs:2
fetchAndRender @ dash.mjs:256
(anonymous) @ dash.mjs:304
(anonymous) @ dash.mjs:6
__awaiter @ dash.mjs:2
updateDashboard @ dash.mjs:299
(anonymous) @ dash.mjs:424
(anonymous) @ dash.mjs:6
__awaiter @ dash.mjs:2
startPolling @ dash.mjs:423
(anonymous) @ dash.mjs:465
(anonymous) @ dash.mjs:6
__awaiter @ dash.mjs:2
start @ dash.mjs:429
(anonymous) @ dash.mjs:468
```

also

```
Unable to perform long poll update:  SyntaxError: Unexpected token < in JSON at position 0 dash.mjs:315
    at dash.mjs:283
    at Generator.next (<anonymous>)
    at fulfilled (dash.mjs:3)
    at <anonymous>
```

server response is:
```html
<html><head><title>s~github-health : uncaught application failure</title><body><pre>

<br></pre></body></html>
```

### PR DESCRIPTION
**Pull request by samuelli**
Fixes #239

### CODE REVIEW

File: src/server/apis/dash-data.ts [hunk 1]
```diff
@@ -307,14 +307,18 @@ export async function fetchIncomingData(
       }
 
       if (newCommits.length && relevantReview) {
+        // Commit can be null.
+        const url = relevantReview.commit ?
```
Comment (gauntface) [inline src/server/apis/dash-data.ts]: would be make more sense to set the URL to null here and have the UI not create an anchor tag (I'm assuming that's what it's doing).

Comment (samuelli) [reply src/server/apis/dash-data.ts]: It doesn't create an anchor tag.
