### PR TITLE
Fix post install

### LINKED ISSUE #519: Github App Post Install has a race condition
After installing the github app we redirect to post-install page that confirms the installation and redirects afterwards to the org config.

At the moment there is a race condition between this page and the webhook triggering and completing a setup step.

### PR DESCRIPTION
**Pull request by gauntface**
Fixes #519

### CODE REVIEW

File: src/server/dash-server.ts [hunk 1]
```diff
@@ -123,13 +126,62 @@ export class DashServer {
             return;
           }
 
-          const installDetails = await githubAppModel.getInstallation(
-              Number(request.query.installation_id));
-          if (!installDetails) {
-            response.status(400).send('Invalid installation ID.');
+          const userRecord = await userModel.getUserRecordFromRequest(request);
+          if (!userRecord) {
+            // User may not be signed but have project-health setup and
```
Comment (samuelli) [inline src/server/dash-server.ts]: signed in but has the project-heath app installed, so we should redirect.

File: src/server/utils/generate-github-app-token.ts [hunk 2]
```diff
@@ -21,19 +18,22 @@ export async function generateGithubAppToken(installId: number):
...
   const responseBody = await response.json();
   if (!responseBody.token) {
-    console.error('Unabel to g');
     throw new Error('Unable to generate to GitHub App auth token.');
   }
   return responseBody.token;
 }
 
-async function generateJWT(appId: number, certPath: string) {
+export async function generateJWT() {
```
Comment (samuelli) [inline src/server/utils/generate-github-app-token.ts]: What is JWT? Can we rename/add comments?
